irregulars = {"decir": "dir", "hacer": "har", "caber": "cabr", "haber": "habr", "saber": "sabr", "poner": "pondr", "poder": "podre", "salir":"saldr", "tener":"tendr", "querer": "querr", "valer": "valdr", "venir": "vendr"}

pastpart = {"romper":"roto", "escribir": "escrito", "volver": "vuelto", "ver":"visto",
"morir":"muerto", "abrir":"abeirto", "cubrir":"cubierto", "poner":"puesto", "hacer":"hecho",
"decir":"dicho", "descubrir":"descubierto"}

stemchange = {"dorm":"duerm"}
stemchangepast = {"querer":"quis", "tener": "tuv", "estar":"estuv", "andar":"anduv", "caber":"cup", "conducir":"conduj","decir":"dij", "hacer":"hic", "poder":"pud", "poner": "pus", "producir":"produj", "saber":"sup","traducir":"traduj", "traer":"traj", "venir":"vine"}

eiestemchange1 = ['acertar', 'divertirse', 'pensar', 'atender', 'empezar', 'perder', 'atravesar', 'encender', 'preferir', 'calentar', 'encerrar', 'querer', 'cerrar', 'entender', 'recomendar', 'comenzar', 'fregar', 'remendar', 'confesar', 'gobernar', 'sentar', 'helar', 'sentir', 'sugerir', 'defender', 'mentir', 'tropezar', 'descender', 'negar', 'despertar', 'nevar']
eiestemchange2 = ['comenzar', 'empezar', 'acertar', 'adherir', 'adquirir', 'advertir', 'apretar', 'arrepentir', 'ascender', 'asentir', 'atender', 'atravesar', 'calentar', 'cerrar', 'circunvenir', 'comenzar', 'conferir', 'to \r\n                      confer', 'confesar', 'consentir', 'contener', 'contravenir', 'convenir', 'convertir', 'defender', 'descender', 'desmembrar', 'desmentir', 'despertar', 'desplegar', 'detener', 'diferir', 'to \r\n                      differ', 'digerir', 'discernir', 'disentir', 'empezar', 'encender', 'encerrar', 'encomendar', 'enmendar', 'ensangrentar', 'entender', 'enterrar', 'to \r\n                      bury, inter', 'entretener', 'entrevenir', 'extender', 'fregar', 'gobernar', 'heder', 'helar', 'to \r\n                      freeze, gell, ice over', 'herir', 'hervir', 'inferir', 'to \r\n                      infer', 'ingerir', 'intervenir', 'invernar', 'to \r\n                      hibernate, winter', 'invertir', 'malherir', 'manifestar', 'mantener', 'mentar', 'mentir', 'merendar', 'negar', 'nevar', 'obtener', 'ofender', 'pensar', 'perder', 'pervertir', 'preferir', 'to \r\n                      prefer', 'presentir', 'prevenir', 'querer', 'recomendar', 'referir', 'to \r\n                      refer', 'regar', 'remendar', 'to \r\n                      improve, patch, mend, repair', 'renegar', 'replegar', 'requerir', 'restregar', 'retener', 'reventar', 'segar', 'sembrar', 'sentar', 'sentir', 'serrar', 'sosegar', 'sostener', 'soterrar', 'to \r\n                      bury underground, inter', 'subarrendar', 'sugerir', 'temblar', 'tender', 'tener', 'tentar', 'transferir', 'to \r\n                      transfer', 'tropezar', 'venir']
eiestemchange3 = ['advertir', 'cerrar', 'comenzar', 'convertir', 'defender', 'divertir', 'empezar', 'encender', 'entender', 'enterrar', 'herir', 'hervir', 'invertir', 'mentir', 'negar', 'nevar', 'pensar', 'perder', 'preferir', 'querer', 'recomendar', 'referir', 'regar', 'sentar', 'sentir', 'sugerir']

eistemchange1 = ['repetir - to repeat', 'conseguir', 'repetir', 'corregir', 'despedir', 'to fire/to say goodbye', 'seguir', 'elegir', 'servir', 'to serve', 'impedir', 'medir', 'vestirse', 'perseguir']
eistemchange2 = ['competir', 'concebir', 'conseguir', 'contradecir', 'corregir', 'decir', 'derretir', 'despedir', 'ir', 'desvestir', 'elegir', 'embestir', 'engreir', 'ir', 'expedir', 'gemir', 'impedir', 'investir', 'maldecir', 'medir', 'pedir', 'perseguir', 'predecir', 'proseguir', 'reelegir', 'reexpedir', 'regir', 'rendir', 'ir', 'repetir', 'revestir', 'seguir', 'servir', 'subseguir', 'ir', 'trasgredir']
eistemchange3 = ['competir', 'conseguir', 'corregir', 'despedir', 'elegir', 'impedir', 'medir', 'pedir', 'repetir', 'seguir', 'servir', 'vestir']

ouestemchange1 = ['ar - to dream', 'absolver', 'doler', 'recordar', 'to remember', 'acordarse (de)', 'dormir', 'remover', 'almorzar', 'encontrar', 'resolver', 'aprobar', 'envolver', 'retorcer', 'cocer', 'llover', 'revolver', 'colgar', 'morder', 'rogar', 'conmover', 'moler', 'soler', 'contar', 'morir', 'sonar', 'costar', 'mostrar', 'ar', 'demoler', 'mover', 'torcer', 'demostrar', 'poder', 'tronar', 'to thunder', 'devolver', 'probar', 'volar', 'disolver', 'promover']
ouestemchange2 = ['forzar', 'absolver', 'acordar', 'acostar', 'almorzar', 'alongar', 'amoblar', 'apostar', 'to \r\n                            post a bet, wager', 'aprobar', 'asolar', 'avergonzar', 'cocer', 'colar', 'colgar', 'concordar', 'conmover', 'consolar', 'contar', 'to \r\n                            count, matter', 'costar', 'degollar', 'demoler', 'demostrar', 'desaprobar', 'descolgar', 'to \r\n                            unhang, let down, lower', 'descontar', 'desosar', 'destorcer', 'devolver', 'disolver', 'doler', 'dormir', 'encontrar', 'engrosar', 'envolver', 'forzar', 'holgar', 'hollar', 'llover', 'moler', 'morder', 'morir', 'mostrar', 'mover', 'oler', 'poblar', 'probar', 'promover', 'recordar', 'to \r\n                            remind, remember', 'reforzar', 'remorder', 'remover', 'renovar', 'repoblar', 'resolver', 'resollar', 'resonar', 'retorcer', 'revolcar', 'revolver', 'rodar', 'rogar', 'solar', 'soldar', 'to \r\n                            weld, solder', 'soler', 'soltar', 'sonar', 'ar', 'torcer', 'tostar', 'tronar', 'to \r\n                            thunder', 'volar', 'volcar', 'volver']
ouestemchange3 = ['almorzar', 'colgar', 'contar', 'costar', 'devolver', 'doler', 'dormir', 'encontrar', 'jugar', 'llover', 'morir', 'mostrar', 'mover', 'poder', 'probar', 'recordar', 'resolver', 'rogar', 'sonar', 'torcer', 'volver']

eiestemchange = eiestemchange1 + eiestemchange2 + eiestemchange3
eistemchange = eistemchange1 + eistemchange2 + eistemchange3
ouestemchange = ouestemchange1 + ouestemchange2 + ouestemchange3

zcoverbs1 = ['abastecer', 'aborrecer', 'acontecer', 'adolecer', 'to \r\n                      suffer', 'aducir', 'agradecer', 'amanecer', 'anochecer', 'aparecer', 'to \r\n                      show up, appear', 'apetecer', 'balbucir', 'carecer', 'compadecer', 'comparecer', 'to \r\n                      appear', 'conducir', 'conocer', 'crecer', 'decrecer', 'deducir', 'to \r\n                      deduce, deduct, infer', 'desagradecer', 'desaparecer', 'to \r\n                      disappear', 'desconocer', 'desentumecer', 'desfallecer', 'desfavorecer', 'deslucir', 'desmerecer', 'desobedecer', 'desvanecer', 'embellecer', 'embrutecer', 'empobrecer', 'enaltecer', 'enardecer', 'encarecer', 'endurecer', 'enflaquecer', 'enfurecer', 'enloquecer', 'enmohecer', 'enmudecer', 'ennegrecer', 'ennoblecer', 'enorgullecer', 'enriquecer', 'enrojecer', 'ensombrecer', 'ensordecer', 'enternecer', 'entorpecer', 'entristecer', 'envejecer', 'establecer', 'estremecer', 'fallecer', 'favorecer', 'florecer', 'fortalecer', 'fosforecer', 'guarecer', 'humedecer', 'inducir', 'introducir', 'languidecer', 'lucir', 'merecer', 'nacer', 'negrecer', 'obedecer', 'ofrecer', 'to \r\n                      offer', 'oscurecer', 'padecer', 'palidecer', 'parecer', 'permanecer', 'pertenecer', 'prevalecer', 'producir', 'reaparecer', 'reblandecer', 'reconocer', 'recrudecer', 'reducir', 'relucir', 'reproducir', 'resplandecer', 'restablecer', 'seducir', 'traducir', 'yacer']
zcoverbs2 = ['conocer', 'apetecer', 'conducir', 'introducir', 'merecer', 'ofrecer', 'parecer', 'permanecer', 'producir', 'traducir']

zoverbs1 = ['torcer', 'convencer', 'ejerecer', 'vencer']

zcoverbs = zcoverbs1 + zcoverbs2
zoverbs = zoverbs1

presentirregulars = {"caber":"quepo", "caer":"caigo", "dar":"doy", "decir":"digo", "estar":"estoy", "hacer":"hago", "ir":"voy", "poner":"pongo", "saber":"se (with accent)", "salir":"salgo", "tener":"tengo", "valer":"valgo", "venir":"vengo", "ver":"veo"}